CREATE TABLE INOTIFY_EVENTS (EVENT_DATE DATE NOT NULL, PATH VARCHAR(75) NOT NULL, EVENT_TYPE VARCHAR(25) NOT NULL, USER VARCHAR(25) NOT NULL, USER_GROUP VARCHAR(25) NOT NULL, TX_ID INT(20) NOT NULL, PRIMARY KEY (TX_ID));

INSERT INTO INOTIFY_EVENTS (EVENT_DATE,PATH,EVENT_TYPE,USER,USER_GROUP,TX_ID) VALUES (20161105,'<path to file>','CREATE','<user>','<user group>',5);